#!/usr/bin/env bash
set -euo pipefail
command -v jq >/dev/null 2>&1 || exit 0

# sdd-index.sh: Manage feature index
# Supports: rebuild, show, help, validate subcommands

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$PROJECT_DIR"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Source sdd-lib.sh
# shellcheck source=/dev/null
. "$SCRIPT_DIR/sdd-lib.sh"

# Singleton guard — only one index rebuild runs at a time per project
sdd_lock_or_exit "index-rebuild"

# Feature root
SDD_FEATURE_ROOT="${SDD_FEATURE_ROOT:-${CLAUDE_PROJECT_DIR:-.}/.features}"
INDEX_FILE="$SDD_FEATURE_ROOT/INDEX.md"

# Parse common args
sdd_parse_common_args "$@"

# Subcommand
SUBCOMMAND="${SDD_ARGS[0]:-show}"

# Helper: get created date from brief.md
get_created_date() {
  local fdir="$1"
  sdd_frontmatter_value "$fdir/brief.md" "created" 2>/dev/null || echo "unknown"
}

# Helper: get updated date from brief.md
get_updated_date() {
  local fdir="$1"
  sdd_frontmatter_value "$fdir/brief.md" "updated" 2>/dev/null || echo "unknown"
}

# Helper: build JSON feature object for JSON output
build_feature_json() {
  local fdir="$1"
  local fid="$2"
  local feature_path="${3:-$fid}"
  local feature_group phase desc_json short long short_source long_source created updated task_json total completed

  feature_group="$(sdd_feature_path_group "$feature_path")"
  phase="$(sdd_feature_phase "$feature_path")"
  desc_json="$(sdd_feature_description_json "$feature_path")"
  short="$(printf '%s\n' "$desc_json" | jq -r '.short')"
  long="$(printf '%s\n' "$desc_json" | jq -r '.long // empty')"
  short_source="$(printf '%s\n' "$desc_json" | jq -r '.short_source')"
  long_source="$(printf '%s\n' "$desc_json" | jq -r '.long_source // empty')"
  created="$(get_created_date "$fdir")"
  updated="$(get_updated_date "$fdir")"

  # Get task counts
  if [ -f "$fdir/tasks.md" ]; then
    task_json="$(sdd_task_summary_cheap "$fdir/tasks.md")"
    total="$(printf '%s\n' "$task_json" | jq -r '.total')"
    completed="$(printf '%s\n' "$task_json" | jq -r '.completed')"
  else
    total="0"
    completed="0"
  fi

  jq -n \
    --arg fid "$fid" \
    --arg feature_path "$feature_path" \
    --arg feature_dir "$fdir" \
    --arg feature_group "$feature_group" \
    --arg title "$(sdd_frontmatter_value "$fdir/brief.md" "title" 2>/dev/null || echo "$fid")" \
    --arg phase "$phase" \
    --arg short "$short" \
    --arg long "$long" \
    --arg short_source "$short_source" \
    --arg long_source "$long_source" \
    --arg created "$created" \
    --arg updated "$updated" \
    --arg completed "$completed" \
    --arg total "$total" \
    '{
      feature: $fid,
      feature_id: $fid,
      feature_path: $feature_path,
      feature_dir: $feature_dir,
      feature_group: (if $feature_group == "" then null else $feature_group end),
      title: $title,
      phase: $phase,
      description: $short,
      description_long: (if $long == "" then null else $long end),
      description_source: $short_source,
      description_long_source: (if $long_source == "" then null else $long_source end),
      created: $created,
      updated: $updated,
      tasks: {
        completed: ($completed | tonumber),
        total: ($total | tonumber)
      }
    }'
}

# Rebuild subcommand: generate INDEX.md
rebuild() {
  local quiet="${1:-}"

  # Scan all feature directories
  local feature_paths_array=()
  if [ -d "$SDD_FEATURE_ROOT" ] && [ -n "$(ls -A "$SDD_FEATURE_ROOT" 2>/dev/null)" ]; then
    while IFS= read -r feature_path; do
      [ -n "$feature_path" ] || continue
      feature_paths_array+=("$feature_path")
    done < <(sdd_iter_feature_paths)
  fi

  # Build INDEX.md content
  local content=""
  local updated_date
  updated_date="$(date +%Y-%m-%d)"

  # Count open/closed features
  local total_count=0
  local closed_count=0
  local open_count=0
  local features_json_array="[]"

  local build_json=0
  [ -z "$quiet" ] && sdd_is_json_mode && build_json=1

  for feature_path in "${feature_paths_array[@]}"; do
    local fid fdir
    fid="$(sdd_feature_path_id "$feature_path")"
    fdir="$SDD_FEATURE_ROOT/$feature_path"
    local phase
    phase="$(sdd_feature_phase "$feature_path")"
    [ "$phase" = "close" ] && closed_count=$((closed_count + 1)) || open_count=$((open_count + 1))
    total_count=$((total_count + 1))

    # Build JSON feature object only when needed for output
    if [ "$build_json" = "1" ]; then
      local fj
      fj="$(build_feature_json "$fdir" "$fid" "$feature_path")"
      features_json_array="$(printf '%s\n' "$features_json_array" | jq --argjson feat "$fj" '. += [$feat]')"
    fi
  done

  # Header
  content+="# Feature Index

> Auto-generated by \`sdd index rebuild\` on $updated_date. DO NOT EDIT.

**$total_count features** | $closed_count closed | $open_count open | Updated: $updated_date

## Overview

| # | Feature | Phase | Tasks | Updated |
|---|---------|-------|-------|---------|"
  content+=$'\n'

  # Overview table rows
  local row_num=1
  for feature_path in "${feature_paths_array[@]}"; do
    local fid fdir
    fid="$(sdd_feature_path_id "$feature_path")"
    fdir="$SDD_FEATURE_ROOT/$feature_path"
    local phase task_progress updated

    phase="$(sdd_feature_phase "$feature_path")"
    updated="$(get_updated_date "$fdir")"

    # Get task progress
    if [ -f "$fdir/tasks.md" ]; then
      local task_json total completed
      task_json="$(sdd_task_summary_cheap "$fdir/tasks.md")"
      completed="$(printf '%s\n' "$task_json" | jq -r '.completed')"
      total="$(printf '%s\n' "$task_json" | jq -r '.total')"
      task_progress="$completed/$total"
    else
      task_progress="—"
    fi

    # Add table row with anchor link
    content+="| $row_num | [$feature_path](#$feature_path) | $phase | $task_progress | $updated |"
    content+=$'\n'
    row_num=$((row_num + 1))
  done

  content+=$'\n'
  content+="## Features

"

  # Per-feature detail sections
  local first=1
  for feature_path in "${feature_paths_array[@]}"; do
    local fid fdir
    fid="$(sdd_feature_path_id "$feature_path")"
    fdir="$SDD_FEATURE_ROOT/$feature_path"
    local title phase description created updated task_json total completed

    if [ $first -eq 0 ]; then
      content+=$'---\n\n'
    fi
    first=0

    title="$(sdd_frontmatter_value "$fdir/brief.md" "title" 2>/dev/null || echo "$fid")"
    phase="$(sdd_feature_phase "$feature_path")"
    local desc_json_md short_desc
    desc_json_md="$(sdd_feature_description_json "$feature_path")"
    short_desc="$(printf '%s\n' "$desc_json_md" | jq -r '.short')"
    if [ ${#short_desc} -gt 200 ]; then
      short_desc="${short_desc:0:197}..."
    fi
    description="$short_desc"
    created="$(get_created_date "$fdir")"
    updated="$(get_updated_date "$fdir")"

    # Get task counts
    if [ -f "$fdir/tasks.md" ]; then
      task_json="$(sdd_task_summary_cheap "$fdir/tasks.md")"
      total="$(printf '%s\n' "$task_json" | jq -r '.total')"
      completed="$(printf '%s\n' "$task_json" | jq -r '.completed')"
    else
      total="0"
      completed="0"
    fi

    content+="### $feature_path

**$title** | $phase | $completed/$total tasks

**Created**: $created
**Updated**: $updated

$description
"
  done

  # Write atomically
  sdd_write_file_atomic "$INDEX_FILE" "$content"

  # Normalise mtime so INDEX.md is strictly >= the parent dir mtime bumped by
  # the atomic `mv` on APFS/ext4 (otherwise `find -newer INDEX.md` keeps
  # returning `.features/` itself on every subsequent show(), causing an
  # infinite rebuild loop).
  touch "$INDEX_FILE"

  # Output
  if [ -z "$quiet" ]; then
    if sdd_is_json_mode; then
      local data_json
      data_json="$(jq -n --argjson features "$features_json_array" '{features: $features}')"
      sdd_json_success "index" "" "none" "" "$data_json"
    else
      sdd_note "Generated $INDEX_FILE with $total_count features"
    fi
  fi

  return 0
}

# Show subcommand: display INDEX.md (rebuild if missing or stale).
# INDEX.md is a derived human-readable dashboard; it rebuilds lazily when a
# caller asks to see it. Staleness = any entry under .features/ is newer than
# INDEX.md itself. `find -newer ... -print -quit` short-circuits on first hit.
show() {
  local needs_rebuild=0
  if [ ! -f "$INDEX_FILE" ]; then
    needs_rebuild=1
  elif [ -d "$SDD_FEATURE_ROOT" ] && \
       [ -n "$(find "$SDD_FEATURE_ROOT" -newer "$INDEX_FILE" -print -quit 2>/dev/null)" ]; then
    needs_rebuild=1
  fi
  [ "$needs_rebuild" -eq 1 ] && rebuild --quiet

  if sdd_is_json_mode; then
    # Build features JSON array from disk
    local features_json="[]"
    if [ -d "$SDD_FEATURE_ROOT" ]; then
      while IFS= read -r feature_path; do
        [ -n "$feature_path" ] || continue
        local fid fdir
        fid="$(sdd_feature_path_id "$feature_path")"
        fdir="$SDD_FEATURE_ROOT/$feature_path"
        local fj
        fj="$(build_feature_json "$fdir" "$fid" "$feature_path")"
        features_json="$(printf '%s\n' "$features_json" | jq --argjson feat "$fj" '. += [$feat]')"
      done < <(sdd_iter_feature_paths)
    fi

    # Emit JSON with features in data section
    local data_json
    data_json="$(jq -n --argjson features "$features_json" '{features: $features}')"
    sdd_json_success "index" "" "none" "" "$data_json"
  else
    cat "$INDEX_FILE"
  fi
}

# Help subcommand
show_help() {
  if sdd_is_json_mode; then
    sdd_help_json \
      "index" \
      "Manage feature index: rebuild, show, and validate INDEX.md" \
      "sdd index {rebuild|show|validate|help} [options]" \
      "$(sdd_common_flags_json)" \
      '[]' \
      '[
        "sdd index",
        "sdd index rebuild",
        "sdd index --json",
        "sdd index validate"
      ]'
  else
    cat <<'EOF'
sdd index — Feature Index Management

Usage: sdd index {rebuild|show|validate|help} [options]

Subcommands:
  rebuild   Generate .features/INDEX.md from disk state
  show      Display INDEX.md content (default if no subcommand given)
  validate  Check INDEX.md consistency against disk state
  help      Show this help

Flags:
  --quiet         Suppress output (rebuild only)
  --json          Output JSON
  --help          Show this help

Examples:
  sdd index rebuild           # Regenerate INDEX.md
  sdd index                   # Display INDEX.md
  sdd index --json            # Get features as JSON array
  sdd index validate          # Check for consistency issues
EOF
  fi
}

# Validate subcommand: check consistency
validate() {
  if [ ! -f "$INDEX_FILE" ]; then
    sdd_fail "index" "precondition" "INDEX.md does not exist. Run 'sdd index rebuild' first." '{}' "" "none"
  fi

  # Get list of features from disk
  local disk_features=()
  if [ -d "$SDD_FEATURE_ROOT" ]; then
    while IFS= read -r feature_path; do
      [ -n "$feature_path" ] || continue
      disk_features+=("$feature_path")
    done < <(sdd_iter_feature_paths)
  fi

  # Extract feature IDs from INDEX.md overview table
  # Table rows look like: | 1 | [0001-sdd-agent-harness](#0001-sdd-agent-harness) | close | 19/19 | 2026-04-02 |
  local index_features=()
  while IFS= read -r line; do
    # Skip header and separator rows
    [[ "$line" =~ ^\|\ *#\  ]] && continue
    [[ "$line" =~ ^\|-+\| ]] && continue
    [[ "$line" =~ ^\|---\| ]] && continue
    # Extract feature path from anchor link: [group/NNNN-name](#group/NNNN-name)
    if [[ "$line" =~ \[([^]]*[0-9]{4}-[^]]+)\]\( ]]; then
      index_features+=("${BASH_REMATCH[1]}")
    fi
  done < <(awk '/^## Overview/,/^## Features/' "$INDEX_FILE")

  local errors=0

  # Check for features on disk but not in INDEX
  for fid in "${disk_features[@]}"; do
    local found=0
    for idx_fid in "${index_features[@]+"${index_features[@]}"}"; do
      if [ "$fid" = "$idx_fid" ]; then
        found=1
        break
      fi
    done
    if [ $found -eq 0 ]; then
      printf 'ERROR: Feature %s found on disk but not in INDEX.md\n' "$fid" >&2
      errors=$((errors + 1))
    fi
  done

  # Check for features in INDEX but not on disk
  for idx_fid in "${index_features[@]+"${index_features[@]}"}"; do
    local found=0
    for fid in "${disk_features[@]}"; do
      if [ "$idx_fid" = "$fid" ]; then
        found=1
        break
      fi
    done
    if [ $found -eq 0 ]; then
      printf 'ERROR: Feature %s in INDEX.md but not found on disk\n' "$idx_fid" >&2
      errors=$((errors + 1))
    fi
  done

  if [ $errors -eq 0 ]; then
    echo "OK — INDEX.md is consistent with disk state (${#disk_features[@]} features)"
    return 0
  else
    echo "FAIL — INDEX.md has $errors inconsistencies. Run 'sdd index rebuild' to fix."
    return 1
  fi
}

# Main dispatch
case "$SUBCOMMAND" in
  rebuild)
    rebuild "${SDD_ARGS[1]:-}"
    ;;
  show)
    show
    ;;
  help)
    show_help
    ;;
  validate)
    validate
    ;;
  *)
    # Default to show
    show
    ;;
esac
